# Generated by Django 4.2.3 on 2023-08-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
    ]
