# Generated by Django 4.2.3 on 2023-08-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.location'),
        ),
    ]
